language: python
python:
  - "3.6"
install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - py.test --cov-config .coveragerc --cov=Api
  - coverage report
after_success:
  - coveralls
  - pytest
